<Project>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <!-- Path to the Bannerlord installation -->
    <GameFolder>C:\Game\Steam\steamapps\common\Mount &amp; Blade II Bannerlord</GameFolder>
    <!-- Mod Configuration Menu (MCM v5) -->
    <McmBinFolder>C:\Game\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\Bannerlord.MBOptionScreen\bin\Win64_Shipping_Client</McmBinFolder>
  </PropertyGroup>
</Project>
